### ISSUE TITLE
[Bug & Mini Request] Mod Compatibility Config Bug

### ISSUE THREAD

**Issue by ZaneDragonBorn** [Globox1997/BackSlot#10]
So There seems to still be a repeated issue no matter what I do (Uninstalling, restarting the game, etc). The Back Slots are only interactable from their original Position. Aka the Mod Compatibility feature only moves the icons but not the interaction points, as seen below. I have followed the instruction that says to restart to enable this feature.
![image](https://user-images.githubusercontent.com/68198648/105563446-13d9a500-5cec-11eb-803d-b58eaea6fd74.png)

**Now on to the Request**
Please link the issues page in Mod Menu.

**Comment by Globox1997** [comment]
That's super weird cause I can't reproduce this bug in a singleplayer world. does this happen only in multiplayer or does it also happen when you have only backslot installed?

**Comment by ZaneDragonBorn** [comment]
This happened in Singleplayer (Can't test in Multiplayer) and I was playing with it with like 290+ mods. The Mods that may cause this issue are Trinkets and Curios API. Otherwise, I don't see any other causes

**Comment by Globox1997** [comment]
I tested with the newest curios api + trinkets + bunch o trinkets and everything worked fine.
I have used this "new" version of backslot where I just updated the networking which shouldn't change any compat so I have no idea what could cause this bug. There has to be another mod which causes trouble, anything you could think of?
This is the version I used:
[backslot-1.1.9.zip](https://github.com/Globox1997/BackSlot/files/5861173/backslot-1.1.9.zip)

**Comment by ZaneDragonBorn** [comment]
I'll try it now

**Comment by ZaneDragonBorn** [comment]
![image](https://user-images.githubusercontent.com/68198648/105619588-17d7f680-5dc2-11eb-8c0d-06136799bd19.png)
Nope seems like it doesn't work. I can't thing of anything that would cause this

**Comment by Globox1997** [comment]
to be clear, you are not asking for a inventory sorting compatibility, the green + the handslot are the slots where the weapons will get displayed when they should get displayed next to (right of) the recipe book?

**Comment by ZaneDragonBorn** [comment]
> to be clear, you are not asking for a inventory sorting compatibility,

In this issue, I'm not asking for Compatibility. I'm asking for a bug fix. I have no idea what would cause this though. the Only mods I can think of that may be Trinkets, Curios, Inventory Profiles, Inventory Tabs, and Inventory Sorting

> he green + the handslot are the slots where the weapons will get displayed when they should get displayed next to (right of) the recipe book?

yes

**Comment by Globox1997** [comment]
They only way to find out which mod makes trouble is to check every single one...

**Comment by ZaneDragonBorn** [comment]
Yeah, I know that. That's why I said the ones I believe may be the cause.

**Comment by Globox1997** [comment]
I've tested rinkets, Curios, Inventory Profiles, and Inventory Sorting on 1.16.5 and still, everything worked fine so far 
Inventory Tabs isn't available on this mc version

**Comment by RyanCR03** [comment]
im using latest version of the mod on 1.16.4 and having a similar problem, so it might be that

**Comment by IdrisQe** [comment]
I'm getting this issue as well. I'm using Trinkets. Just installed Bunch O' Trinkets (the glove slot intersecting is what made me toggle the feature in the first place) and it didn't work correctly. After removing a bunch of mods- surprisingly, the ones I thought _wouldn't_ cause any issues, the problem resolved itself in my test instance. After adding back the mods, the issue resumed. I removed... Quite a few, so I'm going to do some more testing and searching through the logs...

**Comment by IdrisQe** [comment]
This may be the cause? Not sure. It's definitely one of the more notable errors on loading, and mentions entity equipment (inventory?) as well as shifting, which sounds like the kind of thing moving the locations would do. Can't figure out what mod is causing it so this will be some trial and error...
```
[23:34:38] [main/WARN]: @Inject(@At("INVOKE")) Shift.BY=2 on modid.mixins.json:events.MixinLivingEntity::handler$zke000$entityEquip exceeds the maximum allowed value: 0. Increase the value of maxShiftBy to suppress this warning.
java.lang.ClassNotFoundException: Not Enough Crashes deobfuscated stack trace
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:168)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Unknown Source)
	at fudge.notenoughcrashes.stacktrace.ModIdentifier.identifyFromClass(ModIdentifier.java:74)
	at fudge.notenoughcrashes.stacktrace.ModIdentifier.identifyFromThrowable(ModIdentifier.java:49)
	at fudge.notenoughcrashes.stacktrace.ModIdentifier.lambda$identifyFromStacktrace$0(ModIdentifier.java:26)
	at fudge.notenoughcrashes.stacktrace.ModIdentifier.visitChildrenThrowables(ModIdentifier.java:31)
	at fudge.notenoughcrashes.stacktrace.ModIdentifier.identifyFromStacktrace(ModIdentifier.java:26)
	at net.minecraft.class_128.md3da566$lambda$afterFillSystemDetails$0$0(class_128.java:1070)
	at net.minecraft.class_129.method_577(class_129.java:79)
	at net.minecraft.class_128.handler$bgb000$afterFillSystemDetails(class_128.java:1068)
	at net.minecraft.class_128.method_559(class_128.java:65)
	at net.minecraft.class_128.<init>(class_128.java:37)
	at net.minecraft.class_128.method_24305(class_128.java:302)
	at net.minecraft.client.main.Main.main(Main.java:135)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:146)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
java.lang.ClassNotFoundException: net.minecraft.util.crash.CrashReport
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:168)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Unknown Source)
	at fudge.notenoughcrashes.stacktrace.ModIdentifier.identifyFromClass(ModIdentifier.java:74)
	at fudge.notenoughcrashes.stacktrace.ModIdentifier.identifyFromThrowable(ModIdentifier.java:49)
	at fudge.notenoughcrashes.stacktrace.ModIdentifier.lambda$identifyFromStacktrace$0(ModIdentifier.java:26)
	at fudge.notenoughcrashes.stacktrace.ModIdentifier.visitChildrenThrowables(ModIdentifier.java:31)
	at fudge.notenoughcrashes.stacktrace.ModIdentifier.identifyFromStacktrace(ModIdentifier.java:26)
	at net.minecraft.class_128.md3da566$lambda$afterFillSystemDetails$0$0(class_128.java:1070)
	at net.minecraft.class_129.method_577(class_129.java:79)
	at net.minecraft.class_128.handler$bgb000$afterFillSystemDetails(class_128.java:1068)
	at net.minecraft.class_128.method_559(class_128.java:65)
	at net.minecraft.class_128.<init>(class_128.java:37)
	at net.minecraft.class_128.method_24305(class_128.java:302)
	at net.minecraft.client.main.Main.main(Main.java:135)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:146)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
```

**Comment by Globox1997** [comment]
First of all it's quite entertaining to read your comment @IdrisQe :D
I don't know where you are from but I usually read from top to bottom not the other way around xD
Why do you have so many mods installed :D however, the number of mods shouldn't affect anything.

**Comment by IdrisQe** [comment]
Well I put edits at the top when they're important and... I just sort of kept adding edits. Canada, though.
And as for all the mods, because I have a serious problem whenever I'm making a modpack, I throw in EVERY mod I MIGHT want to use, and about 50 mods that only tweak one thing very slightly >.>;; and about 20 performance tweak mods...

**Comment by IdrisQe** [comment]
Honestly though I feel like my modpack is cursed. I remove one more mod to push me over that point, ANY mod, and the glitch with BackSlot's config stops happening. I add one more mod back, ANY mod, and it starts happening again. I don't understand it.
At this rate I might just remove BackSlot...
Or maybe I'll just remove Bunch of Trinkets since it's where the slot's getting overlaid in the first place... Hmm...
I do really want to use BackSlot... Hmmm...

Well either way that can wait for tomorrow I spent 4 hours trying to debug this mess and it's 3:33 AM and i'm sleep deprived so yes

i hope this gets fixed, somehow, or that the cause is figured out, because ... i just want to know what it is at this point, frankly

**Comment by Globox1997** [comment]
oh nice canada :D
I would say, remove backslot cause I don't think I will find out what causes this bug since you already tried to locate incompatibilities but couldn't fit it.
Maybe in a future version, it's magically fixed^^

**Comment by Globox1997** [comment]
[backslot-1.1.10-test.zip](https://github.com/Globox1997/BackSlot/files/6076533/backslot-1.1.10-test.zip)
The only thing I can think of is this - changed the mixin injection point inside the PlayerScreenHandler class for the initialization method. You have to unzip it if you test it out

**Comment by IdrisQe** [comment]
..........
![image](https://user-images.githubusercontent.com/40530630/109868195-37add600-7c1c-11eb-9fdf-93ce7019c9e2.png)
It worked.

Excuse me while I faceplant my desk because oh my gosh-
THANK YOU!

**Comment by Globox1997** [comment]
xD...
I just tested other things and I didn't get good results.
In my estimation I will not be able to solve the problem. 
And I guess, too many mods could lead to different loading times which could change the load order of mods which actually doesn't make real sense but thats the only thing I can think of could cause the mod counting thingy.

**Comment by IdrisQe** [comment]
Honestly I have no idea what it could be at this point. I just decided to remove Bunch of Trinkets and, in the old version of BackSlot, set the config back to normal. Without the Trinkets glove slot there's no overlap, so it's fine! Besides, I probably wasn't going to use most of the BoT Trinkets upon inspection.

Still annoyed I couldn't figure out what was causing the issue though... Oh well.
Thanks for testing things to try and fix it though, even though there was basically no concrete evidence as to the cause!

**Comment by Globox1997** [comment]
I would also like to figure out what causes this bug :D
Thank you too for testing stuff out!

**Comment by IdrisQe** [comment]
I hope you manage to figure it out somehow! It's an odd one for sure >.>
Interestingly I came across another bug with another mod that seemed to just... go away when I removed a certain number of mods, regardless of which ones it was. Unless it was a bug caused by interactions involving 38 different mods which I highly doubt >.>;;;;

**Comment by XxMr1234GamerzxX** [comment]
@Globox1997 would you like to join our discord il send you our modpack MMC version that i use for testing and this has a 100% recreation of this bug

**Comment by XxMr1234GamerzxX** [comment]
its not short

**Comment by Globox1997** [comment]
Mh, as the comments in this Issue say, it's a multi mod problem which is basically much harder to fix than other bugs/incompatibilities. Hope you understand my statement. If you can localize it on a specific mod, I would give it another try

**Comment by Globox1997** [comment]
Added advanced slot moving settings, this may help for compat issue [https://github.com/Globox1997/BackSlot/commit/2be53542f4c5661c9aa0f62ca2ead97e6a1e01af](https://github.com/Globox1997/BackSlot/commit/2be53542f4c5661c9aa0f62ca2ead97e6a1e01af)

**Comment by Globox1997** [comment]
If this still happens on the latest version, reopen this issue.
